### ISSUE TITLE
include issuer name in github issues

### ISSUE THREAD

**Issue by ajm188** [ajm188/slack#28]
original issue opened [here](https://github.com/hacsoc/slacksoc/issues/20).

there are a couple of things to consider:
- slack nicks do not necessarily match with GitHub user names, so we can't @ mention the person
- we should probably grab more user info (first and last names - aren't you glad we make people set those?) and put those in, along with the slack nick

**Comment by a-johnston** [comment]
I figured an easy and understandable solution would be to have slacksoc append something like "opened via slack by Firstname Lastname". Maybe in the future people could tell slacksoc their github username but that doesn't seem necessary atm

**Comment by ajm188** [comment]
> opened via slack by ...

Exactly. I was thinking something along the lines of "issue opened on behalf of <nick> (<full name>)", where the full name is only appended if it available.

> Maybe in the future people could tell slacksoc their GitHub name

probably not going to happen, since I don't see a way to prevent people from lying

**Comment by a-johnston** [comment]
> since I don't see a way to prevent people from lying

Ha. we could authenticate by opening an issue on one of their repos and be something like "close issue within 10 minute window to confirm this is you". I just think for all the reasons to make the bot persistent in any way, this is not that important a reason.

**Comment by ajm188** [comment]
Oh god...

Yeah, also, the bot is currently not persistent _at all_, so we would have to add that as well.

In any case, I think the basic feature is pretty easy, and I'll try to get to it this afternoon, unless someone else wants to tackle it.
